### ISSUE TITLE
Create a cross-app (Ps and XD) plugin sample

### ISSUE THREAD

**Issue by ashryanbeats** [AdobeDocs/uxp-photoshop-plugin-samples#11]
- Use the new manifest (v4)
- Use Spectrum UXP
- Use a panel & modal dialog
- Interact with the document in some way (we can keep this quite basic)

One approach might be to find an existing sample for XD or Ps and make it cross-app.

Note for Kerri and Ash: Where should the sample live? Maybe new repo.

**Comment by bootsie123** [comment]
@ErinFinnegan Hi! Would you mind closing this issue? Merged in PR #37
