### ISSUE TITLE
Create a Secure Storage sample

### ISSUE THREAD

**Issue by ashryanbeats** [AdobeDocs/uxp-photoshop-plugin-samples#12]
- Save data like an API key via plugin UI (probably dialog)
- Reload/read data from storage

**Comment by luninor** [comment]
@ashryanbeats I would like to work on this issue. Can you point me to the relevant secure storage documentation? I found [this](https://www.adobe.io/photoshop/uxp/guides/uxp_guide/uxp-misc/file-access/#secure-storage) but it doesn't provide any code related info.

**Comment by ashryanbeats** [comment]
@luninor yes indeed! :) 

Here is the reference page for secureStorage:
https://www.adobe.io/photoshop/uxp/uxp/reference-js/Modules/uxp/Key-Value%20Storage/SecureStorage/
