### ISSUE TITLE
Create a new sample that Creates & Extracts Zip Files using JS

### ISSUE THREAD

**Issue by ashryanbeats** [AdobeDocs/uxp-photoshop-plugin-samples#15]
There's a specific library developers need to use for this (jszip), so we want to guide them on which one and how to use it.

Use it to:
- Import a zip
    - Import a zip of images
- Export a zip
    - Export artboard(s) to zip
    - Allow user to use file picker to select images/files to zip and save
- Ex
    - Icon generator

**Comment by kerrishotts** [comment]
Library we know works: https://stuk.github.io/jszip/

**Comment by aviral243** [comment]
Hey @ashryanbeats !

Can I work on this one?

**Comment by ashryanbeats** [comment]
@aviral243 I made some notes based on our conversation today

**Comment by bootsie123** [comment]
@ErinFinnegan Hi! Would you mind closing this issue? Merged in PR #39
