### ISSUE TITLE
Create a sample that demonstrate OAuth workflow

### ISSUE THREAD

**Issue by ashryanbeats** [AdobeDocs/uxp-photoshop-plugin-samples#16]
Q: Where should this workflow happen?

A: Via a browser workflow.

1. Redirect through the browser
2. Present auth workflow
3. Give token back to plugin
4. Store in secureStorage

You will likely want to build the plugin and a standalone server app that the plugin can communicate with.

**Comment by luninor** [comment]
@ashryanbeats can I start working on this plugin sample while I am waiting on the response for the manifest updation issue?

**Comment by ErinFinnegan** [comment]
Thanks, Ayan!
