### ISSUE TITLE
Create a JS framework starter sample

### ISSUE THREAD

**Issue by ashryanbeats** [AdobeDocs/uxp-photoshop-plugin-samples#17]
We already have a ui-react-starter sample that shows developers how to get start building plugin UI with React.

We'd like to have a similar starter for other frameworks, for example:

- Angular
- ~Vue~ (covered by #26)
- Svelte
- etc

This issue can broken out by framework so different contributors are welcome to work on a sample for their chosen framework. We recommend that you consider taking up creating the equivalent sample for XD as well.

**Comment by PragatiVerma18** [comment]
Hey @ashryanbeats, would like to work on the Vue Starter sample. Please assign it to me, thanks.

**Comment by ashryanbeats** [comment]
Awesome @PragatiVerma18! I made you a new issue in #26. :)

**Comment by jake-pauls** [comment]
Hey @ErinFinnegan  and @kerrishotts, I'm currently exploring a ton with integrating Svelte/UXP. Is it okay if I grab an issue for a Svelte starter sample?

**Comment by ErinFinnegan** [comment]
Absolutely, @jake-pauls ! Go for it!

**Comment by bootsie123** [comment]
Hi @ErinFinnegan! I noticed the current Vue sample is a bit different from a typical Vue starter sample. Would it be okay if I created a new issue to update that?

**Comment by ErinFinnegan** [comment]
I don't know if you need to create an entirely new issue... you could just do some PRs... but you can create an issue if you think that's more convenient.
