### ISSUE TITLE
ui-react-starter: missing package-lock.json

### ISSUE THREAD

**Issue by rsylvian** [AdobeDocs/uxp-photoshop-plugin-samples#2]
Hi there!

Thanks for providing these great examples. I've been able to successfully load a few of them but I was having an issue with `ui-react-starter`. When running `yarn install` the `preinstall` script is kicking off and it is requiring a `package-lock.json` that doesn't exist. 

Since the guide for this plugin is recommending to use `yarn` it is safe to remove the use of the `preinstall` script because the sole purpose of `npm-force-resolutions` is to mimic yarn's dependencies resolution without needing yarn. We will also need to commit the `yarn.lock` to make it work properly.

With these changes I am able to run the plugin on my end:

![Screen Shot 2020-10-20 at 6 10 41 PM](https://user-images.githubusercontent.com/1449325/96660877-958df100-12ff-11eb-9984-f64b80d769eb.png)

Happy to submit a PR if needed but the repo is currently not open to outside contributions :)

**Comment by ashryanbeats** [comment]
Hi @rsylvian, we'd love for you to submit a PR! It looks like we need a `CONTRIBUTING` file on the repo.

**Comment by aviral243** [comment]
@ashryanbeats Hey! I'd like to work on this issue and 3 others related to ui-react-starter
