### ISSUE TITLE
React sample doesn't work

### ISSUE THREAD

**Issue by c4kaci** [AdobeDocs/uxp-photoshop-plugin-samples#31]
Hi,

I followed your instructions.
I installed dependencies: **npm install**       -> it's OK

**npm run build** :
PS E:\Develop\Photoshop\UXP\uxp-photoshop-plugin-samples\ui-react-starter> npm run build

> com.adobe.uxp.starter.react@1.0.0 build E:\Develop\Photoshop\UXP\uxp-photoshop-plugin-samples\ui-react-starter
> webpack --mode development

[webpack-cli] Failed to load 'E:\Develop\Photoshop\UXP\uxp-photoshop-plugin-samples\ui-react-starter\webpack.config.js' config
[webpack-cli] Invalid options object. Copy Plugin has been initialized using an options object that does not match the API schema.
 - options[0] should be an object:
   object { patterns, options? }
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! com.adobe.uxp.starter.react@1.0.0 build: `webpack --mode development`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the com.adobe.uxp.starter.react@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\kaci\AppData\Roaming\npm-cache\_logs\2021-06-21T15_19_11_850Z-debug.log
PS E:\Develop\Photoshop\UXP\uxp-photoshop-plugin-samples\ui-react-starter> 

**node --version**
v14.17.1
**npm --version**
6.14.13

**npm list webpack-cli**
com.adobe.uxp.starter.react@1.0.0 E:\Develop\Photoshop\UXP\uxp-photoshop-plugin-samples\ui-react-starter
`-- webpack-cli@4.7.2

**OS**: Windows 10
**IDE:** VS Code: 1.57.1

Thx 
kaci

**Comment by jake-pauls** [comment]
Hello! :wave:

Have you modified the `webpack.config.js` file at all? I believe this issue stems from the `copy-webpack-plugin`, more specifically the options passed to it... although the options in the sample's configuration look okay.

If you haven't modified that file at all, you could try to remove the `copyUnmodifed` option (still worked fine in my dev environment).

```
plugins: [
    //new CleanWebpackPlugin(),
    new CopyPlugin(['plugin'], {})
]
```

Mind you, this may result in some issues while running the webpack dev server if you try to develop off of this locally.

**Comment by c4kaci** [comment]
Hi Jake,

Thank you for your quick  answer.
No, I didn't  modified webpack.config.js.
I tried your variation with same error.

I have same error with **ui-vue-starter** also.

Thx
kaci

**Comment by c4kaci** [comment]
The problem was caused by the wrong webpack version 

`npm WARN css-loader@2.1.1 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.`

Solution: I installed manually the right webpack version:
`npm install --save-dev webpack@^4.0.0`

/kaci

**Comment by c4kaci** [comment]
The problem was caused by the wrong webpack version 

`npm WARN css-loader@2.1.1 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.`

Solution: I installed manually the right webpack version:
`npm install --save-dev webpack@^4.0.0`

/kaci
