### ISSUE TITLE
Create a sample integrating Firebase

### ISSUE THREAD

**Issue by pklaschka** [AdobeDocs/uxp-photoshop-plugin-samples#44]
As per this request: https://forums.creativeclouddeveloper.com/t/anyone-using-firebase-with-their-uxp-plugin/3640

I'm not 100 % sure if it's possible to integrate the Firebase libraries, meaning that this includes first evaluating if it is possible to do so.

**Comment by ashikka** [comment]
@pklaschka @ErinFinnegan  Can you assign this issue to me? I'd like to work on it.
