### ISSUE TITLE
Migrate the CEP Invisible Extension Panel to UXP

### ISSUE THREAD

**Issue by ErinFinnegan** [AdobeDocs/uxp-photoshop-plugin-samples#47]
- Take this [sample CEP panel](https://github.com/Adobe-CEP/CEP-Resources/tree/master/CEP_11.x/Samples/CEP_HTML_Invisible_Extension-10.0)
- Make use of our [CEP Getting Started Guide](https://github.com/Adobe-CEP/Getting-Started-guides#readme)
- Migrate the panel to UXP
- Write a guide and/or blog post about the experience

**Comment by ThisIsMrAli** [comment]
@ErinFinnegan I can handle this one. Please let me know if no one else is already have started this.

**Comment by ErinFinnegan** [comment]
Go for it!

**Comment by ThisIsMrAli** [comment]
@ErinFinnegan Sure, I have 2 pull requests waiting, I will start this right after finished those:)

**Comment by ErinFinnegan** [comment]
Are your other two PRs waiting for approval? If so provide the links and I’ll see what I can do…

**Comment by ThisIsMrAli** [comment]
@pklaschka @ErinFinnegan im staring working on this. Please let me know if you have any suggestion or tip.

**Comment by pklaschka** [comment]
I have assigned the issue to you now :-)

I don't have any particular suggestions, but please let us know if you need anything or have any questions!

Thanks,
Pablo

**Comment by ThisIsMrAli** [comment]
@pklaschka Sure Thanks :)

**Comment by ThisIsMrAli** [comment]
@pklaschka @ErinFinnegan 
Hi There,
I have already done this and made a [pull request ](https://github.com/AdobeDocs/uxp-photoshop-plugin-samples/pull/77). Please let me know if a blog post or guide is needed.

Thanks
