### ISSUE TITLE
UXP plugin sample that utilizes TypeScript and @photoshop types

### ISSUE THREAD

**Issue by ErinFinnegan** [AdobeDocs/uxp-photoshop-plugin-samples#56]
From the Photoshop roadmap: https://trello.com/c/jHpH0I7T

**Comment by pklaschka** [comment]
The types are at https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/photoshop and can be installed using `npm I -D @types/photoshop`.

It's important to mention that they don't include UXP types (i.e., stuff from the `uxp` module), but only types for the host APIs.

**Comment by jardicc** [comment]
What are the plans for the other UXP types?

**Comment by ashikka** [comment]
@ErinFinnegan @pklaschka Can you assign this issue to me?
