### ISSUE TITLE
ui-react-starter: provide functional react sample

### ISSUE THREAD

**Issue by AAverin** [AdobeDocs/uxp-photoshop-plugin-samples#6]
Modern react development practices favour functional react and hooks rather than classes. Having a sample with classes can confuse new developers who don't yet have a lot of experience.

It would be great to either have current starter re-written in a functional way or provide a functional starter.

**Comment by ashryanbeats** [comment]
RE hooks: position/size of UI elements are not immediately known in UXP as they would be in the browser. You'll need to listen for a "resize" event if you're getting weird results. And let us know if you're having trouble working around this.
