### ISSUE TITLE
How to open a new layer instead of opening a new tab?

### ISSUE THREAD

**Issue by aldisonll** [AdobeDocs/uxp-photoshop-plugin-samples#64]
I'm building a plugin to grab icons from the plugin to photoshop and this is my code which works fine, but I want to create a new layer with the icon/image inside and not open a new tab...

`const tempFolder = await fs.getTemporaryFolder()`
`const file_entry = await tempFolder.getEntry(iconName)`
`await app.open(file_entry)`

![image](https://user-images.githubusercontent.com/34491203/146966207-7a74daf3-7970-4f33-a5ed-5d3b468179e0.png)

**Comment by ErinFinnegan** [comment]
👋 Hi! [Please ask this in the forums](https://forums.creativeclouddeveloper.com/c/photoshop/63).

**Comment by aldisonll** [comment]
Thanks!
