### ISSUE TITLE
tailwindcss and UXP

### ISSUE THREAD

**Issue by ThisIsMrAli** [AdobeDocs/uxp-photoshop-plugin-samples#74]
Hello, I have configured [hello-world-panel-js-sample](https://github.com/AdobeDocs/uxp-photoshop-plugin-samples/tree/main/hello-world-panel-js-sample) with [tailwindcss](https://tailwindcss.com/). I think using tailwindcss in uxp is really time saver.
I can make a pull request if you are interested but im not sure how can i push the branch to make PR.

Please let me know.

**Comment by pklaschka** [comment]
That sounds awesome! Please go ahead and create a pull request in the way I described in the other issue if you'd like. I love to add this here.

**Comment by ThisIsMrAli** [comment]
@pklaschka i've already done this. Please check it out [here](https://github.com/AdobeDocs/uxp-photoshop-plugin-samples/pull/76).
